### PR TITLE
Improves performance by avoiding creating anonymous object every #matches call

### PR DESCRIPTION
**Pull request by tiagofsilva**
This PR:
- fixes a problem the main module had, where an anonymous class was being created on every call to #matches.
- comes up with some small refactors to improve code readability and whatnot.

### CODE REVIEW

**Comment by gvc** [comment]
Just out of curiosity, could we run a benchmark to see the performance difference?

**Comment by lbrito1** [comment]
@gvc @tiagofsilva I ran the following benchmark:

```ruby
require "benchmark"

module MatchingExceptions
# ...
end

ME = MatchingExceptions

puts Benchmark.measure {
  count = 0
  1_000_000.times do
    string = ('a'..'z').to_a.shuffle.join

    def foo(string)
      raise StandardError.new(string)
    rescue ME.matches(string)
      count += 1
    end
  end
}
```

`count` and `string` were used to avoid possible CPU branch prediction optimizations. 

Performance was similar in both versions, with this PR performing ~5% better (on my box, ~8.5s vs 8.1s wall time). Memory usage must be significantly better on this PR though.

**Comment by lbrito1** [comment]
Both approaches had identical results with [memory_profiler](https://github.com/SamSaffron/memory_profiler):

```
Total allocated: 191300000 bytes (3200000 objects)
Total retained:  0 bytes (0 objects)

allocated memory by gem
-----------------------------------
 191300000  other

allocated memory by file
-----------------------------------
 191300000  benchmark.rb

allocated memory by location
-----------------------------------
 191300000  benchmark.rb:48

allocated memory by class
-----------------------------------
 128900000  String
  58400000  Array
   4000000  Range

allocated objects by gem
-----------------------------------
   3200000  other

allocated objects by file
-----------------------------------
   3200000  benchmark.rb

allocated objects by location
-----------------------------------
   3200000  benchmark.rb:48

allocated objects by class
-----------------------------------
   2900000  String
    200000  Array
    100000  Range
```

**Comment by tiagofsilva** [comment]
That's weird, I could bet that memory would somewhat improve because we don't create an object on every `matches` call anymore.

**Pull request merged**
